### ISSUE TITLE
Ingresos

### ISSUE THREAD

**Issue by wilmix** [sistemaHergo/hergo#1]
Crear columna que muestre almacen de cabezera
Filtro Almacen para cargar solamente datos del almacen en uso

**Comment by gabriel-chavez** [comment]
Se agregaron y modificaron las siguientes funciones:
filtros, reporte por gestiones, dolares-bolivianos, anulado, numero de movimiento y filtro por almacen

**Comment by wilmix** [comment]
Agregar anulado a la columna de estado.
Tipo de movimiento fijo según formulario seleccionado. por ahora tenemos Compras Locales, Ingreso importaciones y Anulación Egreso
Title dinámico según pagina donde se este - mostrar los mismos que los títulos de cada pagina. 
Cambio calculo de Costo unitarios de Formulario de Compras locales según plantilla excel.
