### ISSUE TITLE
Observaciones Ingresos

### ISSUE THREAD

**Issue by wilmix** [sistemaHergo/hergo#2]
* Agregar filtro de tipo de movimiento
* Agregar opcion de todos en almacenes 
* Fechas en formato dd-mm-aaaa
* orden de los botones Fecha, Almacen,Tipo de movimiento ....lado a lado.
* Error en orden en todas las columnas q tienen numeros con decimales.
* Mensaje cargando mientras se crea la tabla
* boton para borrar filtros o recargar la pagina
* Aplicar funcionalidad en buscar principal para que busque directamente solo la primera columna num y al hacer enter muestre el detalle del  registro.

**Comment by gabriel-chavez** [comment]
- Agregar filtro de tipo de movimiento...............**SOLUCIONADO**
- Agregar opcion de todos en almacenes............**SOLUCIONADO**
- Fechas en formato dd-mm-aaaa...........**SOLUCIONADO**
- orden de los botones Fecha, Almacen,Tipo de movimiento ....lado a lado............**SALAS**
- Error en orden en todas las columnas q tienen numeros con decimales............**SOLUCIONADO**
- Mensaje cargando mientras se crea la tabla...........**TIENE POR DEFECTO**
- boton para borrar filtros o recargar la pagina............**SALAS**
- Aplicar funcionalidad en buscar principal para que busque directamente solo la primera columna num y al hacer enter muestre el detalle del registro............**SOLUCIONADO**
