### ISSUE TITLE
Ingresos 2

### ISSUE THREAD

**Issue by wilmix** [sistemaHergo/hergo#3]
* Desplazar vista de ingreso siguiente sin usar lupa con teclado o botones de desplasamiento directamente
* Bug Bug formulario de ingreso Articulo detalle muestra solo la primera palabra
* Orden en los select filtros de ingreso
* Orden  código de articulo en formulario de ingreso

**Comment by gabriel-chavez** [comment]
Desplazar vista de ingreso siguiente sin usar lupa con teclado o botones de desplasamiento directamente
Bug Bug formulario de ingreso Articulo detalle muestra solo la primera palabra **SOLUCIONADO**
Orden en los select filtros de ingreso **???????????????**
Orden código de articulo en formulario de ingreso    **?????????**?**??????????????**
