### ISSUE TITLE
Compras Locales

### ISSUE THREAD

**Issue by wilmix** [sistemaHergo/hergo#4]
1.  Alerta para posible error en el costo unitario, cuando la diferencia sea + del 15% o - del 15% del costo unitario ponderado.
2.  Mostrar el monto de la factura y precio unitario de documento en el formulario de ingreso de compras locales y en el mostrar detalles en ingresos. 
3.  Se guardara el monto de factura en la base de datos "totaldoc" y el monto de credito fiscal en el campo "creditofiscal" de la tabla "ingdetalle"
4.  Para el caso de Compra sin factura sera SF en lugar de vacio, para poder filtrar.
5.  Crear un campo para guardar costo de fletes que no se tuvieron en cuenta como muestra la factura siguiente:
(https://cloud.githubusercontent.com/assets/23664201/24978932/65a58986-1fa0-11e7-9900-22aeadd46fc4.jpg
ADJUNTO EXCEL PARA EJEMPLO
[CL-EJEMPLO COMPRAS LOCALES.xlsx](https://github.com/sistemaHergo/hergo/files/917845/CL-EJEMPLO.COMPRAS.LOCALES.xlsx)

**Comment by gabriel-chavez** [comment]
1. Alerta para posible error en el costo unitario, cuando la diferencia sea + del 15% o - del 15% del costo unitario ponderado...............**SE AGREGO**
2. Mostrar el monto de la factura y precio unitario de documento en el formulario de ingreso de compras locales y en el mostrar detalles en ingresos. ..............**SE AGREGO**
3. Se guardara el monto de factura en la base de datos "totaldoc" y el monto de credito fiscal en el campo "creditofiscal" de la tabla "ingdetalle" ..............**SE AGREGO**
4. Para el caso de Compra sin factura sera SF en lugar de vacio, para poder filtrar. ..............**SE AGREGO**
5. Crear un campo para guardar costo de fletes que no se tuvieron en cuenta como muestra la factura siguiente:
(https://cloud.githubusercontent.com/assets/23664201/24978932/65a58986-1fa0-11e7-9900-22aeadd46fc4.jpg **SALAS** ☺
ADJUNTO EXCEL PARA EJEMPLO
CL-EJEMPLO COMPRAS LOCALES.xlsx

**Comment by gabriel-chavez** [comment]
test
