### ISSUE TITLE
Egresos

### ISSUE THREAD

**Issue by wilmix** [sistemaHergo/hergo#5]
1. Mostrar Precio (tabla precio) y Saldo (igual que ingresos) a los formularios Nota de entrega Venta Caja
2. Despues de crear un egreso no se borran totales y observaciones
3. Añadir id nombre del vendedor para Ventas Caja y Notas de entrega.
4. Filtro de Cliente en egresos consulta no funciona al igual que en ingresos.

**Comment by gabriel-chavez** [comment]
Mostrar Precio (tabla precio) y Saldo (igual que ingresos) a los formularios Nota de entrega Venta Caja **(solucionado)**
Despues de crear un egreso no se borran totales y observaciones **(solucionado)** 
Añadir id nombre del vendedor para Ventas Caja y Notas de entrega. **(no se tiene la vista)**
Filtro de Cliente en egresos consulta no funciona al igual que en ingresos. **(no se puede mostrar un select con mas de 13000 opciones)**
